### ISSUE TITLE
Renaming sliders

### ISSUE THREAD

**Issue by MingboPeng** [tt-acm/Colibri.Grasshopper#1]
Iterator can not re-check the connected sliders' name when it is changed, unless reconnect it.

**Comment by bhowes-tt** [comment]
Yeah I've noticed this... you have to trigger the component to solve again - changing a slider's nickname doesn't cause the solution to expire.

Should we just add this info to the error message? 'Please rename your sliders and re-connect the steps input to this component to make it solve again' or something like that.

**Comment by MingboPeng** [comment]
or we can recheck all Sliders and Steps again before set it to run. 
Here is the same problem with Steps, Iterator cannot pick up whatever changed after connected.
![image](https://cloud.githubusercontent.com/assets/9031066/21398045/f7c05b0a-c773-11e6-9bdc-64fccfa1f92d.png)

**Comment by bhowes-tt** [comment]
'or we can recheck all Sliders and Steps again before set it to run.'  We check every time the component solves and it isn't flying.  The issue is that changing a connected slider's nickname doesn't trigger the component to solve  again.

The steps issue might be a separate thing - changing a list should trigger the iterator to solve again, which should update that little dialog box.  If that isn't happening, it's a separate bug (and should become a new issue).

**Comment by bhowes-tt** [comment]
Hooked into a slider event to handle this.  Also opened a new issue for the Steps bug - #3
