### ISSUE TITLE
Detach tt-acm/Colibri.Grasshopper from bhowes-tt/Colibri.Grasshopper

### ISSUE THREAD

**Issue by MingboPeng** [tt-acm/Colibri.Grasshopper#27]
to make the "tt-acm/Colibri.Grasshopper" as "root parent" repo, not forked from "bhowes-tt/Colibri.Grasshopper".

1. we can ask Github staff to extract this repo from  "bhowes-tt/Colibri.Grasshopper".
2. transfer "Colibri.Grasshopper' ownership
3. or switch the relationship: let "bhowes-tt/Colibri.Grasshopper" fork from "tt-acm/Colibri.Grasshopper"

**Comment by bhowes-tt** [comment]
@MingboPeng - I'd prefer to keep it as-is ... the graph shows the natural history of the project.  As long as you work in this repo moving forward as discussed (use branches in this repo for risky / in-process development instead of on forks in your repo), we shouldn't have any more pull request issues.
